# Generated by Django 4.0.1 on 2022-01-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Digite seu nome')),
                ('email', models.CharField(max_length=200, verbose_name='Digite seu email')),
            ],
        ),
    ]
