# Generated by Django 4.0.1 on 2022-02-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_professores'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='professores',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
