# Generated by Django 4.0.1 on 2022-02-05 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_clientes_status_professores_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='telefone',
            field=models.CharField(default=0, max_length=15, verbose_name='Digite seu telefone'),
            preserve_default=False,
        ),
    ]
